//! Read-only completion waits tied to one exact operating-system process incarnation.

use runtrol_provider::ProcessIdentity;

/// A retained process object whose completion is independent of PID reuse.
#[derive(Debug)]
pub struct ProcessExit {
    #[cfg(windows)]
    handle: std::os::windows::io::OwnedHandle,
}

impl ProcessExit {
    /// Retain the exact process before awaiting its exit. Does not signal or alter that process.
    ///
    /// # Errors
    /// Refuses missing, inaccessible or replaced processes, and platforms without this wait surface.
    pub fn open(expected: ProcessIdentity) -> std::io::Result<Self> {
        #[cfg(windows)]
        {
            use std::os::windows::io::{AsHandle as _, FromRawHandle as _, OwnedHandle};
            use windows_sys::Win32::System::Threading::{
                OpenProcess, PROCESS_QUERY_LIMITED_INFORMATION,
            };
            // The standard synchronization right is not generated by windows-sys 0.61.
            const SYNCHRONIZE: u32 = 0x0010_0000;
            #[expect(
                unsafe_code,
                reason = "OpenProcess returns the exact read-only handle retained below"
            )]
            // SAFETY: plain access flags and PID, no inherited handle, and null is checked before ownership.
            let raw = unsafe {
                OpenProcess(
                    PROCESS_QUERY_LIMITED_INFORMATION | SYNCHRONIZE,
                    0,
                    expected.pid(),
                )
            };
            if raw.is_null() {
                return Err(std::io::Error::last_os_error());
            }
            #[expect(
                unsafe_code,
                reason = "the successful kernel open transfers ownership exactly once"
            )]
            // SAFETY: this successful open is owned nowhere else and is closed by OwnedHandle.
            let handle = unsafe { OwnedHandle::from_raw_handle(raw) };
            let started = crate::process_tree::windows_start_from_handle(handle.as_handle())
                .map_err(std::io::Error::other)?;
            if started != expected.started() {
                return Err(std::io::Error::other(
                    "the process incarnation changed before its exit was watched",
                ));
            }
            Ok(Self { handle })
        }
        #[cfg(not(windows))]
        {
            let _unsupported = expected;
            Err(std::io::ErrorKind::Unsupported.into())
        }
    }

    /// Await the retained process's exit through the shared kernel pool, without a polling clock.
    ///
    /// Cancelling this future unregisters the wait and leaves the retained object available to wait again.
    ///
    /// # Errors
    /// Reports an unavailable completion event without claiming that the process ended.
    #[cfg_attr(
        not(windows),
        expect(
            clippy::unused_async,
            clippy::unused_self,
            reason = "unsupported platforms retain the same asynchronous interface"
        )
    )]
    pub async fn wait(&self) -> std::io::Result<()> {
        #[cfg(windows)]
        {
            use std::os::windows::io::AsHandle as _;
            crate::contain::job::wait::signaled(self.handle.as_handle())
                .await
                .map_err(std::io::Error::other)
        }
        #[cfg(not(windows))]
        {
            Err(std::io::ErrorKind::Unsupported.into())
        }
    }
}

#[cfg(all(test, windows))]
mod tests {
    use super::*;
    use std::io::{Read as _, Write as _};
    use std::os::windows::process::CommandExt as _;
    use std::process::{Child, Command, Stdio};
    use std::time::Duration;

    struct Fixture(Child);
    #[expect(
        clippy::expect_used,
        reason = "the synthetic child must be stopped and joined even when its assertion fails"
    )]
    impl Drop for Fixture {
        fn drop(&mut self) {
            if self
                .0
                .try_wait()
                .expect("inspect exact fixture child")
                .is_none()
            {
                self.0.kill().expect("stop exact fixture child");
            }
            self.0.wait().expect("join exact fixture child");
        }
    }

    #[test]
    #[ignore = "subprocess fixture entered only by the completion test"]
    fn process_wait_fixture() {
        if std::env::var_os("RUNTROL_PROCESS_WAIT_FIXTURE").is_none() {
            return;
        }
        std::io::stdin()
            .read_exact(&mut [0])
            .expect("wait for parent's release");
    }

    #[tokio::test]
    async fn exact_exit_wait_refuses_another_birth_and_survives_cancellation() {
        let mut child = Fixture(
            Command::new(std::env::current_exe().expect("test executable"))
                .args([
                    "--exact",
                    "process_exit::tests::process_wait_fixture",
                    "--ignored",
                    "--nocapture",
                ])
                .env("RUNTROL_PROCESS_WAIT_FIXTURE", "1")
                .stdin(Stdio::piped())
                .stdout(Stdio::null())
                .stderr(Stdio::null())
                .creation_flags(windows_sys::Win32::System::Threading::CREATE_NO_WINDOW)
                .spawn()
                .expect("start exact test helper"),
        );
        let identity = crate::process_identity(child.0.id()).expect("fixture birth");
        let wrong =
            ProcessIdentity::new(identity.pid(), identity.started() + 1).expect("different birth");
        assert!(ProcessExit::open(wrong).is_err());
        let completion = ProcessExit::open(identity).expect("retain exact process");
        assert!(
            tokio::time::timeout(Duration::from_millis(10), completion.wait())
                .await
                .is_err()
        );
        child
            .0
            .stdin
            .as_mut()
            .expect("fixture input")
            .write_all(&[1])
            .expect("release helper");
        tokio::time::timeout(Duration::from_secs(3), completion.wait())
            .await
            .expect("exit deadline")
            .expect("exact exit");
        assert!(child.0.wait().expect("join helper").success());
    }
}
