//! Finding the program to run, and skipping the launchers in front of it.
//!
//! # Why this is worth doing at all
//!
//! Both supervised CLIs install on Windows as launchers generated by a package manager. Running one costs a
//! shell process, and in one case an interpreter on top of that, in front of the actual binary. Measured on
//! this machine against the live installations, best of three runs each, `--version` only:
//!
//! | program | through the launcher | as resolved here | saved |
//! |---|---|---|---|
//! | one CLI, resolves to a native binary | 335 ms | 257 ms | 78 ms |
//! | the other, resolves to an interpreter | 349 ms | 260 ms | 89 ms |
//!
//! Roughly 80 milliseconds and one process per session start, which the operator pays every time they open
//! a session.
//!
//! **One number that is deliberately not claimed here.** Running the second CLI's native binary directly,
//! found by hand deep in a vendored platform package, takes 133 ms: 216 ms better than its launcher. This
//! module does not deliver that, because reaching it needs to know where one vendor puts its files. An
//! earlier version of this comment quoted the 216 ms figure as if resolution achieved it, which it does
//! not. The remaining hop is real, worth taking, and belongs to a provider manifest.
//!
//! # Unwrapping is an optimization, never a requirement
//!
//! What this module reads is a **generated** file, written from a fixed template, so recognizing it is
//! structural rather than a guess about any particular vendor. But a template can change.
//!
//! So every failure to unwrap runs the launcher as given. runtrol gets slower; nothing breaks. That is the
//! only acceptable failure direction for a shortcut.
//!
//! And the failure is **not silent.** [`Program::kept_launcher`] says which launcher was kept and why, so a
//! session that starts slowly can explain itself instead of leaving the operator watching a spinner, and so
//! a changed template surfaces as a named condition rather than as a vague slowness.
//!
//! # What this module does not know
//!
//! One of the two launchers resolves to an interpreter plus a script, and that script does its own
//! platform-package lookup to find the real binary. Following that second layer needs knowledge of where
//! one particular vendor puts its files, which belongs in a provider manifest, not here. This module
//! unwraps the launcher and reports honestly that it landed on an interpreter.

use core::fmt;
use std::path::Path;

use runtrol_provider::AbsPath;

use crate::error::SpawnError;

/// How many launchers runtrol will unwrap before giving up.
///
/// More than anything observed. A launcher pointing at a launcher pointing at a launcher is either a cycle
/// or a configuration nobody intended.
const MAX_LAUNCHER_DEPTH: usize = 4;

/// Largest launcher file runtrol will read.
///
/// A generated launcher is a few hundred bytes. Anything larger is not the template this recognizes, and
/// reading an arbitrary file into memory to look for a pattern is not something to do without a bound.
const MAX_LAUNCHER_BYTES: u64 = 8 * 1024;

/// Why a launcher was run as it is rather than unwrapped.
///
/// Every variant costs the operator one process and some startup time, so each one is worth naming. A
/// deployment that suddenly reports [`Self::NoTemplateMarker`] for a program that used to unwrap is a
/// template change, and that is exactly the kind of drift that should be visible rather than felt.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub enum LauncherKept {
    /// The file does not carry the generated template's marker.
    ///
    /// Either somebody wrote this launcher by hand, or the template changed.
    NoTemplateMarker,
    /// Larger than [`MAX_LAUNCHER_BYTES`], so it was not read.
    TooLarge {
        /// How large it actually is.
        bytes: u64,
    },
    /// The file could not be read.
    Unreadable {
        /// What the operating system said.
        detail: String,
    },
    /// The template marker is there but no line invokes anything.
    NoInvocationLine,
    /// The launcher names a program that does not exist.
    TargetMissing {
        /// What it named.
        named: String,
    },
    /// The launcher names itself.
    SelfReferential,
    /// The launcher uses a variable runtrol does not expand.
    ///
    /// Refused rather than half-expanded: a partially expanded path points somewhere real and wrong.
    UnexpandableVariable {
        /// The token that could not be expanded.
        token: String,
    },
    /// The launcher runs an interpreter runtrol could not find.
    InterpreterMissing,
}

impl fmt::Display for LauncherKept {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::NoTemplateMarker => f.write_str(
                "it is not a generated launcher, or the template changed. runtrol will run it as it is",
            ),
            Self::TooLarge { bytes } => {
                write!(f, "it is {bytes} bytes, past the {MAX_LAUNCHER_BYTES} byte read limit")
            }
            Self::Unreadable { detail } => write!(f, "it could not be read: {detail}"),
            Self::NoInvocationLine => f.write_str("no line in it invokes anything"),
            Self::TargetMissing { named } => write!(f, "it names {named:?}, which does not exist"),
            Self::SelfReferential => f.write_str("it names itself"),
            Self::UnexpandableVariable { token } => {
                write!(f, "it uses {token:?}, which runtrol does not expand")
            }
            Self::InterpreterMissing => {
                f.write_str("it runs an interpreter that is not on this machine")
            }
        }
    }
}

/// What kind of thing runtrol ended up pointing at.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProgramKind {
    /// A native executable. Nothing stands between runtrol and the program.
    Native,
    /// An interpreter, with a script as its first argument.
    ///
    /// Reported rather than hidden: a process runtrol did not want is still in the chain, and skipping the
    /// remaining hop needs provider-specific knowledge this module does not have.
    Interpreted,
    /// A launcher that could not be unwrapped.
    ///
    /// Runs correctly and costs an extra process. [`Program::kept_launcher`] says why.
    Launcher,
}

/// A program runtrol is ready to start.
#[derive(Debug, Clone)]
pub struct Program {
    /// The executable to run.
    path: AbsPath,
    /// Arguments that must come before the caller's own.
    leading: Vec<String>,
    /// What was unwrapped on the way here, in the order it was unwrapped.
    ///
    /// An operator debugging "why is it running the wrong version" needs the chain, not the destination.
    via: Vec<AbsPath>,
    /// Why the chain stopped where it did, when it stopped at a launcher.
    kept_launcher: Option<LauncherKept>,
    /// What sort of thing `path` is.
    kind: ProgramKind,
}

impl Program {
    /// The executable to run.
    #[must_use]
    pub const fn path(&self) -> &AbsPath {
        &self.path
    }

    /// Arguments that must precede the caller's own.
    #[must_use]
    pub fn leading(&self) -> &[String] {
        &self.leading
    }

    /// What was unwrapped to get here.
    #[must_use]
    pub fn via(&self) -> &[AbsPath] {
        &self.via
    }

    /// What sort of thing this is.
    #[must_use]
    pub const fn kind(&self) -> ProgramKind {
        self.kind
    }

    /// Why a launcher is still in the chain, when one is.
    ///
    /// `None` when nothing was left behind, which includes the case where there was no launcher to begin
    /// with. Present so a slow start can name its own cause.
    #[must_use]
    pub const fn kept_launcher(&self) -> Option<&LauncherKept> {
        self.kept_launcher.as_ref()
    }

    /// Whether a process runtrol did not want is still in the chain.
    #[must_use]
    pub const fn has_extra_process(&self) -> bool {
        !matches!(self.kind, ProgramKind::Native)
    }
}

/// Find `program` and unwrap any launchers in front of it.
///
/// An absolute path is used as given. Anything else is looked up the way a shell would, honouring `PATHEXT`
/// on Windows.
///
/// # Errors
///
/// [`SpawnError::NotFound`] when nothing by that name exists, [`SpawnError::NotExecutable`] when the
/// resolved path is a directory, [`SpawnError::LauncherTooDeep`] when unwrapping does not terminate.
pub fn resolve(program: &str) -> Result<Program, SpawnError> {
    let mut path = locate(program)?;
    let mut leading: Vec<String> = Vec::new();
    let mut via: Vec<AbsPath> = Vec::new();

    for _ in 0..MAX_LAUNCHER_DEPTH {
        if !is_batch_file(&path) {
            return Ok(finish(path, leading, via, None));
        }
        match unwrap_launcher(&path) {
            Ok(unwrapped) => {
                via.push(path.clone());
                path = unwrapped.target;
                // The launcher's own arguments come before anything already collected: an outer launcher
                // runs an inner one, so its arguments sit further left on the final command line.
                let mut combined = unwrapped.leading;
                combined.extend(leading);
                leading = combined;
            }
            Err(kept) => return Ok(finish(path, leading, via, Some(kept))),
        }
    }

    Err(SpawnError::LauncherTooDeep {
        program: program.to_owned(),
        depth: MAX_LAUNCHER_DEPTH,
    })
}

/// Assemble the resolved program, deciding what sort of thing it turned out to be.
fn finish(
    path: AbsPath,
    leading: Vec<String>,
    via: Vec<AbsPath>,
    kept_launcher: Option<LauncherKept>,
) -> Program {
    let kind = if kept_launcher.is_some() {
        // Stopped at a launcher. Correct, and one process more expensive.
        ProgramKind::Launcher
    } else if !via.is_empty() && !leading.is_empty() {
        // Unwrapped onto an executable that takes a script. The remaining hop is the script's business.
        ProgramKind::Interpreted
    } else {
        ProgramKind::Native
    };
    Program {
        path,
        leading,
        via,
        kept_launcher,
        kind,
    }
}

/// Find the file a program name refers to.
fn locate(program: &str) -> Result<AbsPath, SpawnError> {
    if Path::new(program).is_absolute() {
        let resolved = AbsPath::canonicalize(program).map_err(|error| SpawnError::NotFound {
            program: program.to_owned(),
            searched: format!("the path as given ({error})"),
        })?;
        if resolved.as_std_path().is_dir() {
            return Err(SpawnError::NotExecutable { path: resolved });
        }
        return Ok(resolved);
    }

    // Looked up the way a shell would. Not written by hand: `PATHEXT` ordering, quoted `PATH` entries, and
    // the executable bit on Unix are each easy to get subtly wrong, and getting them wrong means running
    // the wrong program.
    let found = which::which(program).map_err(|_| SpawnError::NotFound {
        program: program.to_owned(),
        searched: searched_description(),
    })?;

    AbsPath::from_os(&found).map_err(|error| SpawnError::Io {
        path: found.display().to_string(),
        detail: error.to_string(),
    })
}

/// Where a lookup would have looked, for the operator to read.
fn searched_description() -> String {
    let separator = if cfg!(windows) { ';' } else { ':' };
    let path = std::env::var("PATH").unwrap_or_default();
    let count = path
        .split(separator)
        .filter(|entry| !entry.is_empty())
        .count();
    match std::env::var("PATHEXT") {
        Ok(extensions) => format!("{count} directories on PATH, with extensions {extensions}"),
        Err(_) => format!("{count} directories on PATH"),
    }
}

/// What a launcher actually runs.
#[derive(Debug, PartialEq, Eq)]
struct Unwrapped {
    /// The program the launcher invokes.
    target: AbsPath,
    /// The arguments the launcher passes before the caller's own.
    leading: Vec<String>,
}

/// Read a launcher and work out what it runs.
///
/// # Errors
///
/// [`LauncherKept`] naming why the launcher has to be run as it is. Not a failure of the spawn: every
/// variant means "slower, and correct".
fn unwrap_launcher(path: &AbsPath) -> Result<Unwrapped, LauncherKept> {
    let metadata =
        std::fs::metadata(path.as_std_path()).map_err(|error| LauncherKept::Unreadable {
            detail: error.to_string(),
        })?;
    if metadata.len() > MAX_LAUNCHER_BYTES {
        return Err(LauncherKept::TooLarge {
            bytes: metadata.len(),
        });
    }
    let text =
        std::fs::read_to_string(path.as_std_path()).map_err(|error| LauncherKept::Unreadable {
            detail: error.to_string(),
        })?;

    // The generated template marks itself by capturing its own directory. Requiring the marker is what
    // keeps this from misreading a launcher somebody wrote by hand.

    if !text.contains("%~dp0") {
        return Err(LauncherKept::NoTemplateMarker);
    }

    let directory = path.parent().ok_or(LauncherKept::NoTemplateMarker)?;
    let invocation = text
        .lines()
        .rev()
        .find(|line| line.contains("%*"))
        .ok_or(LauncherKept::NoInvocationLine)?;

    let mut tokens = quoted_tokens(invocation).into_iter();
    let target_token = tokens.next().ok_or(LauncherKept::NoInvocationLine)?;
    let target_text = expand(&target_token, &directory, &text)?;

    let target = AbsPath::canonicalize(&target_text).map_err(|_| LauncherKept::TargetMissing {
        named: target_text.clone(),
    })?;
    if target.as_std_path().is_dir() {
        return Err(LauncherKept::TargetMissing { named: target_text });
    }
    if target == *path {
        return Err(LauncherKept::SelfReferential);
    }

    // Every remaining token has to expand, or runtrol does not know the full argument list and must not
    // guess at a partial one.
    let mut leading = Vec::new();
    for token in tokens {
        leading.push(expand(&token, &directory, &text)?);
    }

    Ok(Unwrapped { target, leading })
}

/// Whether this path is a Windows batch launcher.
fn is_batch_file(path: &AbsPath) -> bool {
    let Some(name) = path.file_name() else {
        return false;
    };
    let Some((_, extension)) = name.rsplit_once('.') else {
        return false;
    };
    extension.eq_ignore_ascii_case("cmd") || extension.eq_ignore_ascii_case("bat")
}

/// The double-quoted tokens on a line, in order.
///
/// A generated launcher quotes the program and each of its arguments, so reading only quoted tokens steps
/// over the shell bookkeeping around them without needing to understand any of it.
fn quoted_tokens(line: &str) -> Vec<String> {
    let mut tokens = Vec::new();
    let mut current: Option<String> = None;
    for character in line.chars() {
        match (character, &mut current) {
            ('"', None) => current = Some(String::new()),
            ('"', Some(_)) => {
                if let Some(token) = current.take() {
                    tokens.push(token);
                }
            }
            (other, Some(token)) => token.push(other),
            (_, None) => {}
        }
    }
    tokens
}

/// Resolve the two variables a generated launcher uses.
///
/// # Errors
///
/// [`LauncherKept::UnexpandableVariable`] for anything else, and
/// [`LauncherKept::InterpreterMissing`] when the interpreter it names cannot be found.
fn expand(token: &str, directory: &AbsPath, script: &str) -> Result<String, LauncherKept> {
    // The template captures its own directory with a trailing separator, so it writes `<dir>\name` and the
    // naive expansion doubles the separator. Harmless to the OS, and it makes every path runtrol logs look
    // wrong.
    let base = directory.as_str().trim_end_matches(['\\', '/']);

    if let Some(rest) = token.strip_prefix("%dp0%") {
        let joined = format!("{base}\\{}", rest.trim_start_matches(['\\', '/']));
        return Ok(joined);
    }
    if token == "%_prog%" {
        return interpreter(directory, script);
    }
    if token.contains('%') {
        return Err(LauncherKept::UnexpandableVariable {
            token: token.to_owned(),
        });
    }
    Ok(token.to_owned())
}

/// Which interpreter a launcher would use.
///
/// # Errors
///
/// [`LauncherKept::InterpreterMissing`] when neither a bundled interpreter nor one on `PATH` exists.
fn interpreter(directory: &AbsPath, script: &str) -> Result<String, LauncherKept> {
    let base = directory.as_str().trim_end_matches(['\\', '/']);

    for line in script.lines() {
        // A bundled interpreter is assigned from the launcher's own directory. Reading the assignment
        // rather than assuming keeps a bundled interpreter from being replaced by whichever one happens to
        // be on PATH, which would be a different version running the operator's code.
        let Some(assignment) = line.trim().strip_prefix("SET \"_prog=") else {
            continue;
        };
        let Some(rest) = assignment.trim_end_matches('"').strip_prefix("%dp0%") else {
            continue;
        };
        let candidate = format!("{base}\\{}", rest.trim_start_matches(['\\', '/']));
        if Path::new(&candidate).is_file() {
            return Ok(candidate);
        }
    }

    // No bundled interpreter, so the template falls back to a bare name and the shell finds it. Resolving
    // it here means runtrol runs the same one the launcher would have.
    match which::which("node") {
        Ok(found) => Ok(found.display().to_string()),
        Err(_) => Err(LauncherKept::InterpreterMissing),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A scratch directory with launchers in it.
    struct Fixture {
        root: AbsPath,
    }

    impl Fixture {
        fn make(name: &str) -> Self {
            let base = std::env::temp_dir().join(format!("runtrol-resolve-{name}"));
            if base.exists() {
                std::fs::remove_dir_all(&base).expect("clear the previous run");
            }
            std::fs::create_dir_all(&base).expect("create the fixture");
            let root = AbsPath::canonicalize(base.to_str().expect("temp dir is UTF-8"))
                .expect("canonicalize");
            Self { root }
        }

        fn write(&self, name: &str, contents: &str) -> AbsPath {
            let path = self.root.join(name).expect("valid name");
            std::fs::write(path.as_std_path(), contents).expect("write the file");
            AbsPath::canonicalize(path.as_str()).expect("canonicalize")
        }
    }

    impl Drop for Fixture {
        fn drop(&mut self) {
            if let Err(error) = std::fs::remove_dir_all(self.root.as_std_path()) {
                eprintln!("could not clean up {}: {error}", self.root);
            }
        }
    }

    /// The launcher shape observed on this machine for a native binary.
    fn native_launcher(target: &str) -> String {
        format!(
            "@ECHO off\r\nGOTO start\r\n:find_dp0\r\nSET dp0=%~dp0\r\nEXIT /b\r\n:start\r\n\
             SETLOCAL\r\nCALL :find_dp0\r\n\"%dp0%\\{target}\"   %*\r\n"
        )
    }

    /// The launcher shape observed on this machine for an interpreted entry point.
    fn interpreted_launcher(script: &str) -> String {
        format!(
            "@ECHO off\r\nGOTO start\r\n:find_dp0\r\nSET dp0=%~dp0\r\nEXIT /b\r\n:start\r\n\
             SETLOCAL\r\nCALL :find_dp0\r\n\r\nIF EXIST \"%dp0%\\node.exe\" (\r\n  \
             SET \"_prog=%dp0%\\node.exe\"\r\n) ELSE (\r\n  SET \"_prog=node\"\r\n)\r\n\r\n\
             endLocal & goto #_undefined_# 2>NUL || title %COMSPEC% & \"%_prog%\"  \
             \"%dp0%\\{script}\" %*\r\n"
        )
    }

    #[test]
    fn a_launcher_pointing_at_a_native_binary_is_unwrapped() {
        // The measured saving is 219 ms and one process, on every session start.
        let fixture = Fixture::make("native");
        let target = fixture.write("real.exe", "stand-in");
        let launcher = fixture.write("tool.cmd", &native_launcher("real.exe"));

        let unwrapped = unwrap_launcher(&launcher).expect("the template must be recognized");
        assert_eq!(unwrapped.target, target);
        assert!(
            unwrapped.leading.is_empty(),
            "a native launcher passes no arguments of its own"
        );
    }

    #[test]
    fn a_launcher_pointing_at_an_interpreter_keeps_the_script_as_a_leading_argument() {
        let fixture = Fixture::make("interpreted");
        let bundled = fixture.write("node.exe", "stand-in interpreter");
        fixture.write("entry.js", "// stand-in script");
        let launcher = fixture.write("tool.cmd", &interpreted_launcher("entry.js"));

        let unwrapped = unwrap_launcher(&launcher).expect("the template must be recognized");
        assert_eq!(
            unwrapped.target, bundled,
            "the bundled interpreter wins over whatever is on PATH: a different version would run the \
             operator's code"
        );
        assert_eq!(unwrapped.leading.len(), 1);
        assert!(
            unwrapped
                .leading
                .first()
                .is_some_and(|argument| argument.ends_with("entry.js"))
        );
    }

    #[test]
    fn an_interpreted_program_says_a_process_is_still_in_the_chain() {
        let fixture = Fixture::make("interpreted-kind");
        fixture.write("node.exe", "stand-in");
        fixture.write("entry.js", "// stand-in");
        let launcher = fixture.write("tool.cmd", &interpreted_launcher("entry.js"));

        let program = resolve(launcher.as_str()).expect("resolvable");
        assert_eq!(program.kind(), ProgramKind::Interpreted);
        assert!(program.has_extra_process());
        assert!(
            program.kept_launcher().is_none(),
            "the launcher itself was skipped; what remains is the interpreter"
        );
    }

    #[test]
    fn an_unrecognized_launcher_is_kept_and_says_why() {
        // The failure direction that matters, and it must be visible rather than felt. A template change
        // should read as a named condition, not as a session that got mysteriously slower.
        let fixture = Fixture::make("unrecognized");
        let launcher = fixture.write("hand-written.cmd", "@echo off\r\nreal.exe --flag %*\r\n");

        assert_eq!(
            unwrap_launcher(&launcher),
            Err(LauncherKept::NoTemplateMarker)
        );

        let program = resolve(launcher.as_str()).expect("still runnable");
        assert_eq!(program.kind(), ProgramKind::Launcher);
        assert_eq!(program.path(), &launcher, "runs the launcher as it is");
        let reason = program.kept_launcher().expect("a reason is recorded");
        assert!(
            reason.to_string().contains("run it as it is"),
            "the reason has to be readable: {reason}"
        );
    }

    #[test]
    fn a_launcher_pointing_at_nothing_is_kept_and_names_what_was_missing() {
        let fixture = Fixture::make("dangling");
        let launcher = fixture.write("tool.cmd", &native_launcher("absent.exe"));
        match unwrap_launcher(&launcher) {
            Err(LauncherKept::TargetMissing { named }) => {
                assert!(named.ends_with("absent.exe"), "{named}");
            }
            other => panic!("expected a missing target, got {other:?}"),
        }
    }

    #[test]
    fn a_launcher_naming_itself_is_kept_rather_than_looped() {
        let fixture = Fixture::make("selfref");
        let launcher = fixture.write("tool.cmd", &native_launcher("tool.cmd"));
        assert_eq!(
            unwrap_launcher(&launcher),
            Err(LauncherKept::SelfReferential)
        );
    }

    #[test]
    fn a_variable_runtrol_cannot_expand_is_named_rather_than_half_expanded() {
        // A half-expanded path points somewhere real and wrong, which is worse than no shortcut.
        let fixture = Fixture::make("unknownvar");
        let launcher = fixture.write(
            "tool.cmd",
            "@ECHO off\r\nSET dp0=%~dp0\r\n\"%SOMETHING_ELSE%\\real.exe\" %*\r\n",
        );
        match unwrap_launcher(&launcher) {
            Err(LauncherKept::UnexpandableVariable { token }) => {
                assert_eq!(token, "%SOMETHING_ELSE%\\real.exe");
            }
            other => panic!("expected an unexpandable variable, got {other:?}"),
        }
    }

    #[test]
    fn an_oversized_file_is_not_read_looking_for_a_pattern() {
        let fixture = Fixture::make("huge");
        let padding = "rem padding\r\n".repeat(1024);
        let launcher = fixture.write("tool.cmd", &format!("SET dp0=%~dp0\r\n{padding}"));
        match unwrap_launcher(&launcher) {
            Err(LauncherKept::TooLarge { bytes }) => assert!(bytes > MAX_LAUNCHER_BYTES),
            other => panic!("expected a size refusal, got {other:?}"),
        }
    }

    #[test]
    fn a_native_executable_is_not_treated_as_a_launcher() {
        let fixture = Fixture::make("plain");
        let program = fixture.write("real.exe", "stand-in");
        assert!(!is_batch_file(&program));

        let resolved = resolve(program.as_str()).expect("resolvable");
        assert_eq!(resolved.kind(), ProgramKind::Native);
        assert!(!resolved.has_extra_process());
        assert!(resolved.kept_launcher().is_none());
        assert!(resolved.via().is_empty());
    }

    #[test]
    fn batch_extensions_are_recognized_whatever_the_case() {
        let fixture = Fixture::make("case");
        for name in ["a.cmd", "b.CMD", "c.bat", "d.BaT"] {
            assert!(is_batch_file(&fixture.write(name, "x")));
        }
        for name in ["e.exe", "f.js", "g"] {
            assert!(!is_batch_file(&fixture.write(name, "x")));
        }
    }

    #[test]
    fn quoted_tokens_skip_the_shell_bookkeeping_around_them() {
        // The measured interpreted launcher has `endLocal`, a `goto`, and a `title` on the same line as the
        // invocation. Reading only quoted tokens steps over all of it.
        let line = "endLocal & goto #_undefined_# 2>NUL || title %COMSPEC% & \"%_prog%\"  \"%dp0%\\x.js\" %*";
        assert_eq!(quoted_tokens(line), vec!["%_prog%", "%dp0%\\x.js"]);
        assert_eq!(quoted_tokens("no quotes here %*"), Vec::<String>::new());
    }

    #[test]
    fn a_missing_program_names_where_it_looked() {
        // "not found" alone does not tell the operator whether to install something or fix a path.
        let error = resolve("runtrol-nonexistent-program-xyz").expect_err("must not resolve");
        match error {
            SpawnError::NotFound { searched, .. } => {
                assert!(searched.contains("PATH"), "{searched}");
            }
            other => panic!("expected not-found, got {other:?}"),
        }
    }

    #[test]
    fn a_directory_is_not_a_program() {
        let fixture = Fixture::make("dir");
        let directory = fixture.root.join("subdir").expect("valid name");
        std::fs::create_dir_all(directory.as_std_path()).expect("create");
        assert!(matches!(
            resolve(directory.as_str()),
            Err(SpawnError::NotExecutable { .. })
        ));
    }

    #[test]
    fn resolving_records_what_it_skipped() {
        let fixture = Fixture::make("chain");
        fixture.write("real.exe", "stand-in");
        let launcher = fixture.write("tool.cmd", &native_launcher("real.exe"));

        let program = resolve(launcher.as_str()).expect("resolvable");
        assert_eq!(program.via().len(), 1, "one launcher was skipped");
        assert_eq!(program.via().first(), Some(&launcher));
        assert_eq!(program.kind(), ProgramKind::Native);
    }

    #[test]
    fn a_chain_of_launchers_terminates() {
        // A cycle between two launchers must not be followed forever.
        let fixture = Fixture::make("cycle");
        let first = fixture.write("one.cmd", &native_launcher("two.cmd"));
        fixture.write("two.cmd", &native_launcher("one.cmd"));
        assert!(matches!(
            resolve(first.as_str()),
            Err(SpawnError::LauncherTooDeep { .. })
        ));
    }
}
