// Generated by tooling/sync-acp-registry.mjs from the official ACP Registry.
// Runtime performs no registry request and never invokes npx or another downloader.
/// ACP Registry format consumed by the maintainer-only synchronizer.
pub const ACP_REGISTRY_SCHEMA: &str = "1.0.0";
/// SHA-256 of the exact official registry snapshot used for this build.
pub const ACP_REGISTRY_SHA256: &str =
    "60c76d9eaf89ac1b9fb431df31c7ef1c69d186795b094d7d0e5356fcefb80369";
/// Agent declarations in that official snapshot.
pub const ACP_REGISTRY_AGENT_COUNT: usize = 39;
/// Snapshot agents safely expressible as local executable ACP manifests.
pub const ACP_REGISTRY_ADAPTER_COUNT: usize = 30;
/// Official entries served by richer handwritten manifests, including equivalent launch identities.
pub const ACP_REGISTRY_REPLACED_COUNT: usize = 1;
/// Snapshot agents skipped: launch semantics this build cannot express, plus the two this product deliberately
/// does not ship as providers (cline, opencode). Runtrol ships the representative services only.
pub const ACP_REGISTRY_SKIPPED_COUNT: usize = 8;

/// Handwritten providers followed by generated official ACP Registry adapters.
pub const MANIFESTS: &[&str] = &[
    include_str!("../manifests/claude.toml"),
    include_str!("../manifests/codex.toml"),
    include_str!("../manifests/grok.toml"),
    r#"# Generated from the official ACP Registry 1.0.0. Do not edit by hand.
schema = 1
id = "agoragentic-acp"
display_name = "Agoragentic ACP"
icon = "hubot"
kind = "acp"

[bin]
names = ["agoragentic-mcp", "agoragentic-mcp.cmd", "agoragentic-mcp.exe"]

[transport]
argv = ["--acp"]
listen = "stdio"

[help]
install = "npm install --global agoragentic-mcp@1.3.0"
"#,
    r#"# Generated from the official ACP Registry 1.0.0. Do not edit by hand.
schema = 1
id = "amp-acp"
display_name = "Amp ACP"
icon = "hubot"
kind = "acp"

[bin]
names = ["amp-acp", "amp-acp.cmd", "amp-acp.exe"]

[transport]
argv = []
listen = "stdio"
"#,
    r#"# Generated from the official ACP Registry 1.0.0. Do not edit by hand.
schema = 1
id = "autohand"
display_name = "Autohand Code"
icon = "hubot"
kind = "acp"

[bin]
names = ["autohand-acp", "autohand-acp.cmd", "autohand-acp.exe"]

[transport]
argv = []
listen = "stdio"

[help]
install = "npm install --global @autohandai/autohand-acp@0.2.1"
"#,
    r#"# Generated from the official ACP Registry 1.0.0. Do not edit by hand.
schema = 1
id = "claude-acp"
display_name = "Claude Agent ACP"
icon = "hubot"
kind = "acp"

[bin]
names = ["claude-agent-acp", "claude-agent-acp.cmd", "claude-agent-acp.exe"]

[transport]
argv = []
listen = "stdio"

[help]
install = "npm install --global @agentclientprotocol/claude-agent-acp@0.70.0"
"#,
    r#"# Generated from the official ACP Registry 1.0.0. Do not edit by hand.
schema = 1
id = "codebuddy-code"
display_name = "Codebuddy Code"
icon = "hubot"
kind = "acp"

[bin]
names = ["cbc", "cbc.cmd", "cbc.exe", "codebuddy", "codebuddy.cmd", "codebuddy.exe", "cbc-prewarm", "cbc-prewarm.cmd", "cbc-prewarm.exe", "codebuddy-code", "codebuddy-code.cmd", "codebuddy-code.exe"]

[transport]
argv = ["--acp"]
listen = "stdio"

[help]
install = "npm install --global @tencent-ai/codebuddy-code@2.137.1"
"#,
    r#"# Generated from the official ACP Registry 1.0.0. Do not edit by hand.
schema = 1
id = "codex-acp"
display_name = "Codex ACP"
icon = "hubot"
kind = "acp"

[bin]
names = ["codex-acp", "codex-acp.cmd", "codex-acp.exe"]

[transport]
argv = []
listen = "stdio"

[help]
install = "npm install --global @agentclientprotocol/codex-acp@1.6.2"
"#,
    r#"# Generated from the official ACP Registry 1.0.0. Do not edit by hand.
schema = 1
id = "cortex-code"
display_name = "Cortex Code"
icon = "hubot"
kind = "acp"

[bin]
names = ["cortex", "cortex.cmd", "cortex.exe"]

[transport]
argv = ["acp", "serve"]
listen = "stdio"
"#,
    r#"# Generated from the official ACP Registry 1.0.0. Do not edit by hand.
schema = 1
id = "corust-agent"
display_name = "Corust Agent"
icon = "hubot"
kind = "acp"

[bin]
names = ["corust-agent-acp", "corust-agent-acp.cmd", "corust-agent-acp.exe"]

[transport]
argv = []
listen = "stdio"
"#,
    r#"# Generated from the official ACP Registry 1.0.0. Do not edit by hand.
schema = 1
id = "crow-cli"
display_name = "crow-cli"
icon = "hubot"
kind = "acp"

[bin]
names = ["crow-cli", "crow-cli.cmd", "crow-cli.exe"]

[transport]
argv = ["acp"]
listen = "stdio"
"#,
    r#"# Generated from the official ACP Registry 1.0.0. Do not edit by hand.
schema = 1
id = "cursor"
display_name = "Cursor"
icon = "hubot"
kind = "acp"

[bin]
names = ["cursor-agent", "cursor-agent.cmd", "cursor-agent.exe"]

[transport]
argv = ["acp"]
listen = "stdio"
"#,
    r#"# Generated from the official ACP Registry 1.0.0. Do not edit by hand.
schema = 1
id = "deepagents"
display_name = "DeepAgents"
icon = "hubot"
kind = "acp"

[bin]
names = ["deepagents-acp", "deepagents-acp.cmd", "deepagents-acp.exe"]

[transport]
argv = []
listen = "stdio"

[help]
install = "npm install --global deepagents-acp@0.1.7"
"#,
    r#"# Generated from the official ACP Registry 1.0.0. Do not edit by hand.
schema = 1
id = "devin"
display_name = "Devin"
icon = "hubot"
kind = "acp"

[bin]
names = ["devin", "devin.cmd", "devin.exe"]

[transport]
argv = ["acp"]
listen = "stdio"
"#,
    r#"# Generated from the official ACP Registry 1.0.0. Do not edit by hand.
schema = 1
id = "dimcode"
display_name = "DimCode"
icon = "hubot"
kind = "acp"

[bin]
names = ["dim", "dim.cmd", "dim.exe", "dimcode", "dimcode.cmd", "dimcode.exe"]

[transport]
argv = ["acp"]
listen = "stdio"

[help]
install = "npm install --global dimcode@0.3.18"
"#,
    r#"# Generated from the official ACP Registry 1.0.0. Do not edit by hand.
schema = 1
id = "dirac"
display_name = "Dirac"
icon = "hubot"
kind = "acp"

[bin]
names = ["dirac", "dirac.cmd", "dirac.exe"]

[transport]
argv = ["--acp"]
listen = "stdio"

[help]
install = "npm install --global dirac-cli@0.4.37"
"#,
    r#"# Generated from the official ACP Registry 1.0.0. Do not edit by hand.
schema = 1
id = "gemini"
display_name = "Gemini CLI"
icon = "hubot"
kind = "acp"

[bin]
names = ["gemini", "gemini.cmd", "gemini.exe"]

[transport]
argv = ["--acp"]
listen = "stdio"

[help]
install = "npm install --global @google/gemini-cli@0.56.0"
"#,
    r#"# Generated from the official ACP Registry 1.0.0. Do not edit by hand.
schema = 1
id = "github-copilot-cli"
display_name = "GitHub Copilot"
icon = "hubot"
kind = "acp"

[bin]
names = ["copilot", "copilot.cmd", "copilot.exe"]

[transport]
argv = ["--acp"]
listen = "stdio"

[help]
install = "npm install --global @github/copilot@1.0.80"
"#,
    r#"# Generated from the official ACP Registry 1.0.0. Do not edit by hand.
schema = 1
id = "glm-acp-agent"
display_name = "GLM Agent"
icon = "hubot"
kind = "acp"

[bin]
names = ["glm-acp-agent", "glm-acp-agent.cmd", "glm-acp-agent.exe"]

[transport]
argv = []
listen = "stdio"

[help]
install = "npm install --global glm-acp-agent@1.6.0"
"#,
    r#"# Generated from the official ACP Registry 1.0.0. Do not edit by hand.
schema = 1
id = "goose"
display_name = "goose"
icon = "hubot"
kind = "acp"

[bin]
names = ["goose", "goose.cmd", "goose.exe"]

[transport]
argv = ["acp"]
listen = "stdio"
"#,
    r#"# Generated from the official ACP Registry 1.0.0. Do not edit by hand.
schema = 1
id = "harn"
display_name = "Harn"
icon = "hubot"
kind = "acp"

[bin]
names = ["harn", "harn.cmd", "harn.exe"]

[transport]
argv = ["serve", "acp"]
listen = "stdio"
"#,
    r#"# Generated from the official ACP Registry 1.0.0. Do not edit by hand.
schema = 1
id = "junie"
display_name = "Junie"
icon = "hubot"
kind = "acp"

[bin]
names = ["junie", "junie.cmd", "junie.exe"]

[transport]
argv = ["--acp=true"]
listen = "stdio"
"#,
    r#"# Generated from the official ACP Registry 1.0.0. Do not edit by hand.
schema = 1
id = "kilo"
display_name = "Kilo"
icon = "hubot"
kind = "acp"

[bin]
names = ["kilo", "kilo.cmd", "kilo.exe"]

[transport]
argv = ["acp"]
listen = "stdio"
"#,
    r#"# Generated from the official ACP Registry 1.0.0. Do not edit by hand.
schema = 1
id = "kimi"
display_name = "Kimi CLI"
icon = "hubot"
kind = "acp"

[bin]
names = ["kimi", "kimi.cmd", "kimi.exe"]

[transport]
argv = ["acp"]
listen = "stdio"
"#,
    r#"# Generated from the official ACP Registry 1.0.0. Do not edit by hand.
schema = 1
id = "mistral-vibe"
display_name = "Mistral Vibe"
icon = "hubot"
kind = "acp"

[bin]
names = ["vibe-acp", "vibe-acp.cmd", "vibe-acp.exe"]

[transport]
argv = []
listen = "stdio"
"#,
    r#"# Generated from the official ACP Registry 1.0.0. Do not edit by hand.
schema = 1
id = "nova"
display_name = "Nova"
icon = "hubot"
kind = "acp"

[bin]
names = ["nova", "nova.cmd", "nova.exe", "compass", "compass.cmd", "compass.exe"]

[transport]
argv = ["acp"]
listen = "stdio"

[help]
install = "npm install --global @compass-ai/nova@1.1.37"
"#,
    r#"# Generated from the official ACP Registry 1.0.0. Do not edit by hand.
schema = 1
id = "pi-acp"
display_name = "pi ACP"
icon = "hubot"
kind = "acp"

[bin]
names = ["pi-acp", "pi-acp.cmd", "pi-acp.exe"]

[transport]
argv = []
listen = "stdio"

[help]
install = "npm install --global pi-acp@0.0.33"
"#,
    r#"# Generated from the official ACP Registry 1.0.0. Do not edit by hand.
schema = 1
id = "poolside"
display_name = "Poolside"
icon = "hubot"
kind = "acp"

[bin]
names = ["pool-darwin-arm64", "pool-darwin-arm64.cmd", "pool-darwin-arm64.exe", "pool-darwin-amd64", "pool-darwin-amd64.cmd", "pool-darwin-amd64.exe", "pool-linux-arm64", "pool-linux-arm64.cmd", "pool-linux-arm64.exe", "pool-linux-amd64", "pool-linux-amd64.cmd", "pool-linux-amd64.exe", "pool-windows-arm64.exe", "pool-windows-arm64", "pool-windows-amd64.exe", "pool-windows-amd64"]

[transport]
argv = ["acp"]
listen = "stdio"
"#,
    r#"# Generated from the official ACP Registry 1.0.0. Do not edit by hand.
schema = 1
id = "qoder"
display_name = "Qoder CLI"
icon = "hubot"
kind = "acp"

[bin]
names = ["qodercli", "qodercli.cmd", "qodercli.exe"]

[transport]
argv = ["--acp"]
listen = "stdio"

[help]
install = "npm install --global @qoder-ai/qodercli@0.2.14"
"#,
    r#"# Generated from the official ACP Registry 1.0.0. Do not edit by hand.
schema = 1
id = "qwen-code"
display_name = "Qwen Code"
icon = "hubot"
kind = "acp"

[bin]
names = ["qwen", "qwen.cmd", "qwen.exe"]

[transport]
argv = ["--acp", "--experimental-skills"]
listen = "stdio"

[help]
install = "npm install --global @qwen-code/qwen-code@0.22.0"
"#,
    r#"# Generated from the official ACP Registry 1.0.0. Do not edit by hand.
schema = 1
id = "sigit"
display_name = "siGit Code"
icon = "hubot"
kind = "acp"

[bin]
names = ["sigit", "sigit.cmd", "sigit.exe", "sigit-linux-arm64", "sigit-linux-arm64.cmd", "sigit-linux-arm64.exe", "sigit-linux-amd64", "sigit-linux-amd64.cmd", "sigit-linux-amd64.exe", "sigit-win-arm64.exe", "sigit-win-arm64", "sigit-win-amd64.exe", "sigit-win-amd64"]

[transport]
argv = []
listen = "stdio"
"#,
    r#"# Generated from the official ACP Registry 1.0.0. Do not edit by hand.
schema = 1
id = "stakpak"
display_name = "Stakpak"
icon = "hubot"
kind = "acp"

[bin]
names = ["stakpak", "stakpak.cmd", "stakpak.exe"]

[transport]
argv = ["acp"]
listen = "stdio"
"#,
];
