from typing import Any

class NativeError(Exception): ...

class PyIdentity:
    @staticmethod
    def generate() -> PyIdentity: ...
    @staticmethod
    def from_secret(secret: bytes) -> PyIdentity: ...
    def secret_bytes(self) -> bytes: ...
    def public_key_base64(self) -> str: ...
    def self_approval_signature(self, pending_id: str) -> str: ...

class PyRuntimeClient:
    @property
    def initialization_json(self) -> str: ...
    def call(self, operation: str, params_json: str) -> Any: ...
    def subscribe(self, kind: str, params_json: str) -> Any: ...
    def terminal(self, kind: str, params_json: str) -> Any: ...
    def close(self) -> Any: ...

class PySubscription:
    @property
    def started_json(self) -> str: ...
    def next(self) -> Any: ...
    def close(self) -> Any: ...

class PyTerminalEvent:
    @property
    def kind(self) -> str: ...
    @property
    def sequence(self) -> int | None: ...
    @property
    def lost_chunks(self) -> int | None: ...
    @property
    def next_sequence(self) -> int | None: ...
    @property
    def exit_code(self) -> int | None: ...
    def bytes(self) -> bytes: ...

class PyTerminalView:
    @property
    def opened_json(self) -> str: ...
    def initial_screen(self) -> bytes: ...
    def next(self) -> Any: ...
    def call(self, operation: str, params_json: str) -> Any: ...

def connect(
    name: str,
    version: str,
    identity: PyIdentity | None = None,
    grant_json: str | None = None,
) -> Any: ...
def new_mutation_request_id() -> str: ...
