#!/usr/bin/env python3
"""Block generated-attribution markers in commit messages, staged content, and push ranges.

Invoked by the git hooks in `.claude/githooks/` (commit-msg, pre-commit, pre-push), not by
Claude Code. Four CLI modes, exit 0 pass / 1 fail / 2 no-mode.

The rule is not "never mention AI". The rule is "AI is never registered as an authoring
subject" (author / committer / Co-Authored-By / Signed-off-by), and public artifacts stay
subject-neutral. Commit messages carry the wider ban set (bare model names, profanity)
because they are public artifacts; staged file contents only get the attribution scan so
test fixtures and data do not false-positive.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

# 이 파일은 금지 패턴을 리터럴로 들고 있으므로 자기 자신은 검사에서 뺀다.
# **경로를 문자열로 박지 않는다.** 하드코딩하면 파일을 옮기는 순간 자기 면제가 조용히 끊기고
# (실제로 `.claude/hooks/` 에서 `tests/audit/` 로 옮겼을 때 끊겼다) 커밋이 자기 검출기에 막힌다.
# 저장소 루트 기준 상대경로를 실행 시점에 계산한다.
SELF_PATH = Path(__file__).resolve().relative_to(Path(__file__).resolve().parents[2]).as_posix()
ZERO_SHA = "0" * 40

BANNED_PATTERNS = [
    r"co-authored-by",
    r"signed-off-by:\s*(claude|chatgpt|codex|gpt|gemini)",
    r"generated by\s+(chatgpt|claude|codex|gpt|gemini|llm|ai)",
    r"generated with",
    r"ai assisted",
    r"ai-generated",
    r"ai generated",
    r"with claude",
    r"with chatgpt",
    r"with codex",
    r"gpt 협업",
]
COMPILED_PATTERNS = [re.compile(p, re.IGNORECASE) for p in BANNED_PATTERNS]

# 비전문적·비중립 표현. 공개 artifact 인 커밋 메시지에만 적용한다.
# 정상 한국어 단어에 박혀 오탐 나는 표현 (예 '전망했다' 의 '망했') 은 의도적으로 제외.
UNPROFESSIONAL_PATTERNS = [
    r"쓰레기",
    r"병신",
    r"멍청",
    r"바보",
    r"엉망",
    r"개판",
    r"짜증",
    r"존나",
    r"씨발",
    r"닥쳐",
    r"꺼져",
    r"\bshit\b",
    r"\bfuck",
    r"\bdamn\b",
    r"\bcrap\b",
    r"\bwtf\b",
    r"\bstupid\b",
    r"\bidiot\b",
    r"\bdumb(ass)?\b",
]

COMMIT_MESSAGE_BANNED_PATTERNS = [
    *BANNED_PATTERNS,
    r"\b(chatgpt|claude|codex|gpt|gemini|llm|copilot|anthropic|openai)\b",
    r"\bai\b",
    r"생성\s*도구",
    r"작성\s*도구",
    r"모델\s*작성",
    *UNPROFESSIONAL_PATTERNS,
]
COMPILED_COMMIT_MESSAGE_PATTERNS = [re.compile(p, re.IGNORECASE) for p in COMMIT_MESSAGE_BANNED_PATTERNS]

# em dash (U+2014) / en dash (U+2013) 는 커밋 메시지에서도 금지 (CLAUDE.md 강행규칙).
# 이스케이프로 적는다. 리터럴로 적으면 저장소 전수 스캔에서 이 파일 자신이 잡혀
# "위반 0 건" 을 확인할 수 없게 된다 (검출기가 자기 검사를 오염시키는 형태).
DASH_CHARS = (chr(0x2014), chr(0x2013))

COMMIT_TYPES = (
    "추가",
    "수정",
    "개선",
    "변경",
    "삭제",
    "정리",
    "문서",
    "테스트",
    "빌드",
    "릴리즈",
    "보안",
    "성능",
    "리팩터",
    "리팩토링",
    "복구",
    "설정",
    "검증",
)
GENERIC_COMMIT_DETAILS = {
    "작업",
    "수정",
    "변경",
    "업데이트",
    "정리",
    "개선",
    "추가",
    "삭제",
    "wip",
    "fix",
    "update",
    "changes",
}
HANGUL_RE = re.compile(r"[가-힣]")
SKIP_SUFFIXES = {".parquet", ".png", ".jpg", ".jpeg", ".gif", ".ico", ".pdf", ".xlsx", ".xlsm", ".zip"}


def runGit(args: list[str], check: bool = True) -> str:
    """git 을 실행하고 stdout 을 반환한다. check 면 실패 시 RuntimeError."""
    proc = subprocess.run(
        ["git", *args],
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        check=False,
    )
    if check and proc.returncode != 0:
        raise RuntimeError(proc.stderr.strip() or f"git {' '.join(args)} failed")
    return proc.stdout or ""


def findMatches(text: str) -> list[str]:
    """본문에서 AI 기여자 등록 흔적을 찾아 중복 없이 반환한다."""
    return _scan(text, COMPILED_PATTERNS)


def findCommitMessageMatches(text: str) -> list[str]:
    """커밋 메시지 전용 확장 금지 패턴 (모델명·비전문 표현 포함) 을 찾는다."""
    matches = _scan(text, COMPILED_COMMIT_MESSAGE_PATTERNS)
    for ch in DASH_CHARS:
        if ch in text:
            matches.append(f"U+{ord(ch):04X} (긴 줄표)")
    return matches


def _scan(text: str, patterns: list[re.Pattern[str]]) -> list[str]:
    if not text:
        return []
    matches: list[str] = []
    seen: set[str] = set()
    for pattern in patterns:
        for match in pattern.finditer(text):
            snippet = match.group(0)
            key = snippet.lower()
            if key not in seen:
                seen.add(key)
                matches.append(snippet)
    return matches


def reportFailure(title: str, details: list[str]) -> int:
    """실패 사유를 stderr 로 내보내고 1 을 반환한다."""
    print(f"[ai-policy] {title}", file=sys.stderr)
    for detail in details:
        print(f"  - {detail}", file=sys.stderr)
    return 1


def checkCommitMessage(path: str) -> int:
    """커밋 메시지 파일의 금지 패턴 + `성격: 내용` 한글 형식을 검사한다."""
    content = Path(path).read_text(encoding="utf-8", errors="replace")
    failures: list[str] = []

    matches = findCommitMessageMatches(content)
    if matches:
        failures.append(f"금지 패턴 발견: {', '.join(matches)}")

    subject = next(
        (
            line.strip().lstrip("﻿")
            for line in content.splitlines()
            if line.strip() and not line.lstrip().startswith("#")
        ),
        "",
    )
    if not subject:
        failures.append("커밋 제목이 비어 있습니다.")
    elif not HANGUL_RE.search(subject):
        failures.append("커밋 제목은 한글로 작성해야 합니다.")
    elif ":" not in subject:
        failures.append("커밋 제목은 '성격: 변경 내용' 형식이어야 합니다.")
    else:
        commitType, detail = subject.split(":", 1)
        commitType = commitType.strip()
        detail = detail.strip()
        if commitType not in COMMIT_TYPES:
            failures.append(f"커밋 성격은 다음 중 하나여야 합니다: {', '.join(COMMIT_TYPES)}")
        if not detail:
            failures.append("커밋 제목에 실제 변경 내용을 적어야 합니다.")
        elif len(detail) < 6 or detail.lower() in GENERIC_COMMIT_DETAILS:
            failures.append("커밋 제목의 변경 내용이 너무 짧거나 일반적입니다.")
        elif not HANGUL_RE.search(detail):
            failures.append("커밋 제목의 변경 내용은 한글 설명을 포함해야 합니다.")

    if not failures:
        return 0
    return reportFailure("커밋 메시지 규칙을 위반했습니다.", failures)


def stagedFiles() -> list[str]:
    """스테이징된 추가·수정·복사·이름변경 파일 목록."""
    output = runGit(["diff", "--cached", "--name-only", "--diff-filter=ACMR"])
    return [line for line in output.splitlines() if line.strip()]


def _skipFile(filePath: str) -> bool:
    if filePath == SELF_PATH:
        return True
    return Path(filePath).suffix.lower() in SKIP_SUFFIXES


def checkStaged() -> int:
    """스테이징된 blob 내용에서 AI 기여자 흔적을 검사한다."""
    failures: list[str] = []
    for filePath in stagedFiles():
        if _skipFile(filePath):
            continue
        try:
            content = runGit(["show", f":{filePath}"])
        except RuntimeError as exc:
            # 조용히 건너뛰면 검사되지 않은 blob 이 통과한다. 이 게이트는 fail-closed 다.
            failures.append(f"{filePath}: staged blob 을 읽지 못해 검사하지 못했다 ({exc})")
            continue
        matches = findMatches(content)
        if matches:
            failures.append(f"{filePath}: {', '.join(matches)}")
    if not failures:
        return 0
    return reportFailure("스테이징된 내용에 AI 흔적이 포함되어 있습니다.", failures)


def commitRange(base: str | None, head: str) -> list[str]:
    """base..head 커밋 목록. base 가 없으면 아직 원격에 없는 커밋들."""
    if base and base != ZERO_SHA:
        output = runGit(["rev-list", f"{base}..{head}"])
        return [line for line in output.splitlines() if line.strip()]
    output = runGit(["rev-list", head, "--not", "--all"])
    commits = [line for line in output.splitlines() if line.strip()]
    return commits or [head]


def checkCommitRange(base: str | None, head: str) -> int:
    """커밋 메시지 히스토리에 AI 기여자 흔적이 있는지 검사한다."""
    failures: list[str] = []
    for commit in commitRange(base, head):
        message = runGit(["log", "--format=%B", "-n", "1", commit])
        matches = findMatches(message)
        if matches:
            failures.append(f"{commit[:12]}: {', '.join(matches)}")
    if not failures:
        return 0
    return reportFailure("커밋 히스토리에 AI 기여자 흔적이 포함되어 있습니다.", failures)


def changedFilesInRange(base: str | None, head: str) -> list[str]:
    """base..head 에서 추가·수정된 파일 목록."""
    if base and base != ZERO_SHA:
        output = runGit(["diff", "--name-only", f"{base}..{head}", "--diff-filter=ACMR"])
        return [line for line in output.splitlines() if line.strip()]
    files: set[str] = set()
    for commit in commitRange(base, head):
        output = runGit(["diff-tree", "--no-commit-id", "--name-only", "-r", "--diff-filter=ACMR", commit])
        for line in output.splitlines():
            if line.strip():
                files.add(line)
    return sorted(files)


def checkFilesInRange(base: str | None, head: str) -> int:
    """push 범위 파일 내용에서 AI 기여자 흔적을 검사한다."""
    failures: list[str] = []
    for filePath in changedFilesInRange(base, head):
        if _skipFile(filePath) or not Path(filePath).exists():
            continue
        try:
            content = Path(filePath).read_text(encoding="utf-8", errors="replace")
        except OSError:
            # ok: 읽을 수 없는 파일 (심볼릭 링크 끊김·권한) 은 검사 대상이 아니다.
            # 다음 파일로 진행이 보장되고, 못 읽은 파일은 blob 검사(--check-staged)가 다시 본다.
            continue
        matches = findMatches(content)
        if matches:
            failures.append(f"{filePath}: {', '.join(matches)}")
    if not failures:
        return 0
    return reportFailure("변경 파일 내용에 AI 흔적이 포함되어 있습니다.", failures)


def checkPush() -> int:
    """pre-push stdin 의 ref 목록을 읽어 커밋 메시지 + 파일 내용을 검사한다."""
    failures = 0
    for line in sys.stdin:
        parts = line.strip().split()
        if len(parts) != 4:
            continue
        _localRef, localSha, _remoteRef, remoteSha = parts
        if localSha == ZERO_SHA:
            continue
        if checkCommitRange(remoteSha, localSha) != 0:
            failures = 1
        if checkFilesInRange(remoteSha, localSha) != 0:
            failures = 1
    return failures


def buildParser() -> argparse.ArgumentParser:
    """CLI 인자 파서를 만든다."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--check-commit-msg")
    parser.add_argument("--check-staged", action="store_true")
    parser.add_argument("--check-range", nargs=2, metavar=("BASE", "HEAD"))
    parser.add_argument("--check-push", action="store_true")
    return parser


def main() -> int:
    """모드별 검사를 실행한다. 0 통과 / 1 위반 / 2 모드 미지정."""
    args = buildParser().parse_args()
    if args.check_commit_msg:
        return checkCommitMessage(args.check_commit_msg)
    if args.check_staged:
        return checkStaged()
    if args.check_range:
        base, head = args.check_range
        return 1 if (checkCommitRange(base, head) or checkFilesInRange(base, head)) else 0
    if args.check_push:
        return checkPush()
    print("No check mode provided.", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
