/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 25afd0365f190db5cfd2a1399565403c)
interface __BaseEnv_Env {
	PWA_ORIGIN: "https://eddmpython.github.io";
	RELAY_ROUTES: DurableObjectNamespace<import("./src/index").RelayRoute>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "RelayRoute";
	}
	interface StagingEnv {
		PWA_ORIGIN: "https://eddmpython.github.io";
		RELAY_ROUTES: DurableObjectNamespace<import("./src/index").RelayRoute>;
	}
	interface ProductionEnv {
		PWA_ORIGIN: "https://eddmpython.github.io";
		RELAY_ROUTES: DurableObjectNamespace<import("./src/index").RelayRoute>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PWA_ORIGIN">> {}
}
