import { createHash } from "node:crypto";

/// One instruction, tried several ways at once, each in its own worktree.
///
/// The flow this exists for: give the same instruction to N isolated attempts, look at what each produced, keep the
/// one that is best. Runtrol already had every piece of it. A Mission runs a bounded task graph, `isolated_worktree`
/// gives each task its own writable tree, and Gates decide what counts as done. What it did not have was a way in:
/// reaching that flow meant writing a Mission document by hand and then walking a dozen separate commands.
///
/// So this is not a second system beside Mission. It writes the Mission a person would have written, and every
/// guarantee Mission makes still applies to the result.
export type FanOut = {
  /// What every attempt is told to do. The operator's words, unchanged.
  readonly instruction: string;
  /// Where that instruction already lives, relative to the project.
  ///
  /// A path rather than text because Mission binds a task to a reviewed file on disk. Nothing here creates that
  /// file: the operator wrote it, and the digest below is over what they wrote.
  readonly instructionRef: string;
  /// How many attempts run at once.
  readonly branches: number;
  /// The Gate that decides whether an attempt succeeded.
  readonly gateId: string;
  /// Git ref every worktree branches from.
  readonly baseRef: string;
  /// Directories an attempt is allowed to write.
  readonly outputRoots: readonly string[];
  /// Runtime-discovered provider identities assigned round-robin to attempts.
  readonly providerIds: readonly string[];
};

/// The most attempts one fan-out may start.
///
/// Bounded because each attempt owns a worktree and a provider process. Four is already more than a person compares
/// by reading diffs, and the Mission limits below are what actually hold the process count down.
export const MAX_BRANCHES = 4;

/// The fewest that make the flow mean anything.
///
/// One attempt is not a comparison, and the ordinary conversation path already covers it.
export const MIN_BRANCHES = 2;

/// The exact digest a Mission spec must carry for its instruction file.
///
/// Mission binds a task to the bytes of its instruction, so an instruction edited after validation fails rather
/// than silently running something else. So this hashes exactly the bytes already on disk, which are the bytes
/// the operator reviewed. Nothing here creates or rewrites that file.
export function instructionDigest(bytes: string | Uint8Array): string {
  return createHash("sha256").update(bytes).digest("hex");
}

/// A short, stable, filesystem-safe name for one fan-out.
///
/// Derived from the instruction's first words so that a directory listing tells the operator which attempt was
/// which. Falls back to a fixed word rather than to a random one: two fan-outs with unreadable instructions should
/// collide visibly instead of littering the directory with names nobody can match to anything.
export function fanOutName(instruction: string, at: Date): string {
  const words = instruction
    .toLowerCase()
    .replaceAll(/[^a-z0-9]+/gu, "-")
    .split("-")
    .filter(Boolean)
    .slice(0, 4)
    .join("-");
  const stamp = at.toISOString().replaceAll(/[^0-9]/gu, "").slice(0, 14);
  return `${words || "fanout"}-${stamp}`;
}

/// The Mission document, as a person would have written it.
///
/// Tasks carry no `depends_on`, which is what makes them run at once rather than in sequence, and every one gets
/// `isolated_worktree` so no two attempts write the same files. Provider identities are observations selected by
/// the operator from the current Runtime and assigned round-robin, never names built into this extension.
export function missionSpec(name: string, digest: string, fanOut: FanOut): string {
  const branches = Math.min(Math.max(fanOut.branches, MIN_BRANCHES), MAX_BRANCHES);
  if (fanOut.providerIds.length === 0) throw new Error("at least one runtime-discovered provider is required");
  const roots = fanOut.outputRoots.map(tomlString).join(", ");
  const tasks = Array.from({ length: branches }, (_unused, index) => `
[[tasks]]
id = "attempt-${index + 1}"
instruction_ref = ${tomlString(fanOut.instructionRef)}
instruction_sha256 = ${tomlString(digest)}
workspace_mode = "isolated_worktree"
provider_selector = ${tomlString(`runtime:${fanOut.providerIds[index % fanOut.providerIds.length]}`)}
output_roots = [${roots}]
gate_refs = [${tomlString(fanOut.gateId)}]
`).join("");

  return `# Generated by Runtrol so that one instruction can be tried several ways at once.
#
# Every attempt below gets the same instruction and its own isolated worktree, and none depends on another, so they
# run at the same time. The Gate named on each decides whether that attempt succeeded. Read it before starting: this
# is an ordinary Mission document and nothing here is hidden from you.
schema = "runtrol.dev/mission/v1alpha1"
name = ${tomlString(name)}
project_id = ${tomlString(name)}
base_ref = ${tomlString(fanOut.baseRef)}
require_clean_base = true
completion_policy = "choose_one"

[limits]
# One hot provider per attempt, and no more attempts in flight than were asked for.
max_parallel_tasks = ${branches}
max_hot_providers = ${branches}
# One run each. A fan-out is for comparing attempts, not for retrying them; a failed attempt is a result.
max_runs_per_task = 1
max_repair_cycles = 0
stop_on_critical_failure = false
${tasks}`;
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}

/// Whether a branch count is one this flow accepts, and why not when it is not.
export function branchProblem(value: string): string | null {
  const count = Number(value);
  if (!Number.isSafeInteger(count)) return "Enter a whole number of attempts.";
  if (count < MIN_BRANCHES) return `One attempt is not a comparison. Use ${MIN_BRANCHES} or more.`;
  if (count > MAX_BRANCHES) {
    return `Each attempt owns a worktree and an agent process. ${MAX_BRANCHES} is the most at once.`;
  }
  return null;
}
